[project]
name = "motif-detector"
version = "0.1.0"
description = "Exact Discovery of Time Series Motifs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
]
